### ISSUE TITLE
Missing dependency : queue

### ISSUE THREAD

**Issue by sholan** [aker-gateway/Aker#4]
Hello,

I was about to try and test you code on a fresh alpine linux.

When loging to aker-enabled user, I endup with the following stacktrace : 

`Traceback (most recent call last):
  File "/bin/aker/aker.py", line 33, in <module>
    import tui
  File "/bin/aker/tui.py", line 13, in <module>
    import aker
  File "/bin/aker/aker.py", line 35, in <module>
    from snoop import Sniffer
  File "/bin/aker/snoop.py", line 12, in <module>
    from queue import Queue
ImportError: No module named queue
`

I tried to search for something on pip, but didn't find the right one.

Is it possible to specify on installation procedure which module exactly is missing ?
I will be glad to test/specify steps if you'd like so.

regards

**Comment by anazmy** [comment]
Thanks sholan, actually I think I need to change the module name from queue to Queue, I think this mistake was from my testing earlier on python 3,will do the change and notify you

**Comment by anazmy** [comment]
I corrected queue module name, can you please retry now

**Comment by sholan** [comment]
I will have to wait to come back home and test this evening.
Will let you know.

**Comment by sholan** [comment]
Good evening anazmy,

Just tested, it is working (I still have an error once connected with aker shell but it is related to configuration.

Thank you
